-- Drop the unique constraint on tracking_number.
-- Different carriers can reuse tracking numbers, and synced shipments
-- use the carrier's tracking number which may already exist.
-- Our internal tracking number is auto-generated by the generate_tracking_number() trigger.
ALTER TABLE shipments DROP CONSTRAINT IF EXISTS shipments_tracking_number_key;
